name: Deploy Docker

on:
  push:
    branches:
      - main  # 根据需要，修改为您的默认分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4

    - name: Docker Run
      run: |
        docker run -d --restart always --privileged=true -p 35455:35455 --name allinone \
        youshandefeiyang/allinone -tv=true -aesKey=${{ secrets.AESKEY }} \
        -userid=${{ secrets.USERID }} -token=${{ secrets.TOKEN }}

    - name: Wait for Docker service
      run: |
        echo "Waiting for the service to be available..."
        for i in {1..50}; do
          if curl --output /dev/null --silent --head --fail http://localhost:35455/tv.m3u; then
            echo "Service is up!"
            break
          fi
          echo "Service is not ready yet..."
          sleep 5
        done

    - name: Download tv.m3u
      run: |
        curl -o tv.m3u http://localhost:35455/tv.m3u

    - name: Git push assets to "release" branch
      run: |
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b release
        git add .
        git commit -m "${{ env.RELEASE_NAME }}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release
